#!/usr/bin/env python3
"""
Build all Falstad examples of the lecture.

For every module falstad/circuits/<chapter>.py (attribute CIRCUITS, a list of
functions returning (Circuit, check)) this script
  - builds the circuit,
  - simulates it with falstad.Sim and runs the check function
    (numbers asserted there are the ones quoted in the script),
  - writes examples/<chapter>/<name>.txt (File -> Import From Text),
  - writes examples/<chapter>/README.md with clickable links,
  - writes links/<chapter>.tex (used by \\falstad{name} in the LaTeX sources).

Usage: python3 falstad/build_all.py [chapter ...]   (default: all chapters)
"""
import importlib
import os
import sys
import time
import traceback

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "circuits"))

from falstad import Sim  # noqa: E402

ORDER = ["basics", "sources", "references", "bridges", "opamps", "filters",
         "samplehold", "adc", "capstone"]


def modules():
    found = [f[:-3] for f in os.listdir(os.path.join(HERE, "circuits"))
             if f.endswith(".py") and not f.startswith("_")]
    return sorted(found, key=lambda m: (ORDER.index(m) if m in ORDER else 99, m))


def main(argv):
    only = argv[1:]
    failed = []
    os.makedirs(os.path.join(ROOT, "links"), exist_ok=True)
    for mod in modules():
        if only and mod not in only:
            continue
        m = importlib.import_module(mod)
        outdir = os.path.join(ROOT, "examples", mod)
        os.makedirs(outdir, exist_ok=True)
        readme = ["# Falstad examples: %s" % getattr(m, "TITLE", mod), "",
                  "Open a link to start the circuit in the browser, or load the",
                  "`.txt` file with **File → Import From Text** in",
                  "<https://www.falstad.com/circuit/circuitjs.html>.", "",
                  "| File | Content |", "|---|---|"]
        links = ["% generated by falstad/build_all.py -- do not edit\n"]
        for fn in m.CIRCUITS:
            t0 = time.time()
            c = None
            try:
                c, check = fn()
                if check is not None:
                    check(Sim(c))
                status = "ok"
            except Exception as ex:   # report all failures, not only the first
                traceback.print_exc()
                status = "FAILED"
                failed.append("%s/%s: %s" % (mod, fn.__name__, ex))
            if c is None:
                continue
            with open(os.path.join(outdir, c.name + ".txt"), "w") as f:
                f.write(c.text_export())
            url = c.url()
            readme.append("| [%s.txt](%s.txt) ([open in browser](%s)) | %s |" %
                          (c.name, c.name, url, c.title))
            links.append("\\falstaddef{%s}{%s}{%s}\n" % (c.name, mod, url))
            print("%-11s %-28s %-6s %6.1fs  %d elements" %
                  (mod, c.name, status, time.time() - t0, len(c.elms)))
        with open(os.path.join(outdir, "README.md"), "w") as f:
            f.write("\n".join(readme) + "\n")
        with open(os.path.join(ROOT, "links", mod + ".tex"), "w") as f:
            f.write("".join(links))
    if failed:
        print("\nFAILED checks:\n  " + "\n  ".join(failed))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
